import json

def json_to_netscape(input_file, output_file):
    try:
        with open(input_file, 'r') as infile:
            cookies = json.load(infile)
        
        with open(output_file, 'w') as outfile:
            outfile.write('# Netscape HTTP Cookie File
')
            outfile.write('# This file is generated by a script.

')
            for cookie in cookies:
                domain = cookie.get('domain', '')
                if not domain.startswith('.'):
                    domain = '.' + domain  # Ensure domain starts with a dot
                path = cookie.get('path', '/')
                secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
                # Ensure expiration date is an integer
                expiration = int(cookie.get('expirationDate', 0)) if 'expirationDate' in cookie else 0
                name = cookie.get('name', '')
                value = cookie.get('value', '')
                outfile.write(f"{domain}	TRUE	{path}	{secure}	{expiration}	{name}	{value}
")
        print(f"Converted {input_file} to {output_file} successfully.")
    except Exception as e:
        print(f"Error converting {input_file}: {e}")

# Convert Facebook and Instagram cookies
json_to_netscape('fbcookies.json', 'fbcookies_netscape.txt')
json_to_netscape('igcookies.json', 'igcookies_netscape.txt')